### ISSUE TITLE
Issues in Notification

### ISSUE THREAD

**Issue by Soft-TechSolutions** [tirgei/DankMemes#3]
Notification not received when users comments on post

**Comment by tirgei** [comment]
> Notification not received when users comments on post

The app notifications are being sent using Firebase Cloud Functions so you'll need to setup your functions to handle the notifications the way you'd like

**Comment by Soft-TechSolutions** [comment]
> > Notification not received when users comments on post
> 
> The app notifications are being sent using Firebase Cloud Functions so you'll need to setup your functions to handle the notifications the way you'd like

Please you can help me to write firebase Functions if you already write can share me.

**Comment by tirgei** [comment]
> 
> Please you can help me to write firebase Functions if you already write can share me.

You can find it here: https://github.com/tirgei/Dank-Memes-Functions

**Comment by Soft-TechSolutions** [comment]
Thanks

**Comment by Soft-TechSolutions** [comment]
i tried to deploy but getting error.
 
i  deploying functions
i  functions: ensuring required API cloudfunctions.googleapis.com is enabled...
i  functions: ensuring required API cloudbuild.googleapis.com is enabled...
!  functions: missing required API cloudbuild.googleapis.com. Enabling now...
+  functions: required API cloudfunctions.googleapis.com is enabled

Error: Cloud Functions deployment requires the pay-as-you-go (Blaze) billing plan. To upgrade your project, visit the following URL:

https://firebase.google.com/support/faq#functions-runtime

**Comment by tirgei** [comment]
You need to be on the Firebase Blaze plan to deploy functions.. you can click on the link shown there to upgrade from the free plan (Spark) to Blaze

**Comment by Soft-TechSolutions** [comment]
Oh Okay..  Thanks
