### ISSUE TITLE
App İs Stopped

### ISSUE THREAD

**Issue by light123gdf** [tirgei/DankMemes#5]
please help me ı open the project and start app but app is stopped please help me 

demireldaimi@gmail.com

**Comment by tirgei** [comment]
> please help me ı open the project and start app but app is stopped please help me
> 
> [demireldaimi@gmail.com](mailto:demireldaimi@gmail.com)

What is the exact error you're getting?

**Comment by tirgei** [comment]
I'm going to closes this issue as I haven't received any feedback
